services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "2000:2000"   # HOST:CONTAINER (localhost:2000 → backend:2000)
      # Frontend send the POST request to localhost:2000 and then 
      # is routed to port 2000 of the Backend container. 
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"    # HOST:CONTAINER (localhost:3000 → nginx:80)
    depends_on:
      - backend
    restart: unless-stopped   # optional

