services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "2000:2000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"    # host:container (3000 → nginx:80)
    depends_on:
      - backend
    restart: unless-stopped   # optional

