name: CI Pipeline

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Downloads your repo’s code into the runner (like cloning your repo).

    - name: Set up Python
      uses: actions/setup-python@v4 # This sets up Python 3.10 in the runner, just like setting up a virtual environment locally.
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests through Makefile
      run: make test
    
    # - name: Build Docker image
    #   run: docker build -t stress-app . # Even if you don’t push to Docker Hub, you can build and test your image locally inside the CI


